Ver2
CSCI-49900-Fall-2020/Project-chatmanagerlibrary pull request #17
Opened 2020-12-01 19:36 UTC by alleene-lacaba

Created a TeamCommand Class and contains all the functions of Team bot to be call in the main class ChatBotManager class so when ChatbotManager is called and used in project, the user will just call that function and specify in the parameter that it wants to use Teams.

2020-12-01 20:01 UTC, xiaoxiazhang00 commented on README.md
> +**Title:**
duplicate **Title**

2020-12-01 20:02 UTC, xiaoxiazhang00 commented on channel.js
> +
extra line

2020-12-01 20:02 UTC, xiaoxiazhang00 commented on channel.js
> +    }
need to add a line after }

2020-12-01 20:03 UTC, xiaoxiazhang00 commented on channel.js
> +    getChannelData(){
we could use the instance of the class directly instead of creating an extra function for returning the object

2020-12-01 20:07 UTC, xiaoxiazhang00 commented on chatBotManager.js
> +const DiscordCommands = require('./discord-command');
we already have bot class for each channel, you could look into `discordBot.js`, `slackBot.js`

2020-12-01 20:09 UTC, xiaoxiazhang00 commented on discord-command.js
> +        bot.user.setStatus(status);
what's the bot object need to be passed through this function, how could we use this function, do we need to import an external library ?

2020-12-01 20:10 UTC, xiaoxiazhang00 commented on discord-command.js
> +        .catch(message => console.log((message)));
you need to return the promise
`return bot.users.fetch(id)`
catch is just console log the message,  so it's useless.
so you could remove the catch

2020-12-01 20:11 UTC, xiaoxiazhang00 commented on user.js
> +        this.avatatar = platform;
misspell `avatar`, and why `this.avatatar = platform;`

2020-12-01 20:12 UTC, xiaoxiazhang00 commented on user.js
> +    getUserData(){
same as above, no need to have a function to return the object

2020-12-01 20:13 UTC, xiaoxiazhang00 requested changes
please address the issue on each comment

2020-12-01 20:17 UTC, xiaoxiazhang00 commented on discord-command.js
> +        .catch(message => console.log((message)));
by the way sendMessage to user is already implemented in `discordBot.js`

2020-12-18 16:24 UTC, closed without merging

2020-12-18 16:24 UTC, RedolentSun commented
not used